name: ubuntu-printing-app
version: "0.1"
summary: "Printing app which consumes a PDF from content-hub"
description: Printing app which consumes a PDF document from
  content-hub, allows for basic configuration and
  then sends to a CUPS printer.
confinement: strict

apps:
  ubuntu-printing-app:
    command: desktop-launch $SNAP/usr/bin/ubuntu-printing-app --desktop_file_hint=unity8
    plugs:
     - cups-control
     - home
     - network
     - opengl
     - platform
     - unity7
     - unity8

plugs:
  platform:
    interface: content
    content: ubuntu-app-platform1
    target: ubuntu-app-platform
    default-provider: ubuntu-app-platform

parts:
  ubuntu-printing-app:
    build-packages:
     - intltool
     - libcups2-dev
     - libpoppler-qt5-dev
     - qt5-default
     - qt5-qmake
     - qtdeclarative5-dev
     - ubuntu-sdk-qmake-extras
    configflags: [-DCMAKE_INSTALL_PREFIX=/usr, -DCLICK_MODE=off, -DSNAP_MODE=on]
    plugin: cmake
    source: .
    stage-packages:
     - libcups2
     - libqt5printsupport5
    after: [desktop-ubuntu-app-platform]

  environment:
    source: snap/
    plugin: dump
