name: ubuntu-printing-app
version: "0.1"
summary: "Printing app which consumes a PDF from content-hub"
description: Printing app which consumes a PDF document from
  content-hub, allows for basic configuration and
  then sends to a CUPS printer.
confinement: strict

apps:
  ubuntu-printing-app:
    command: desktop-launch $SNAP/usr/bin/ubuntu-printing-app --desktop_file_hint=unity8
    plugs:
     - cups-control
     - home
     - network
     - opengl
     - platform
     - unity7
     - unity8

plugs:
  platform:
    interface: content
    content: ubuntu-app-platform1
    target: ubuntu-app-platform
    default-provider: ubuntu-app-platform

parts:
  ubuntu-printing-app:
    build-packages:
     - intltool
     - libpoppler-qt5-dev
     - qml-module-qttest
     - qml-module-ubuntu-test
     - qt5-default
     - qt5-qmake
     - qtdeclarative5-dev
     - ubuntu-sdk-qmake-extras
     - xvfb
    configflags: [-DCMAKE_INSTALL_PREFIX=/usr, -DCLICK_MODE=off, -DSNAP_MODE=on]
    plugin: cmake
    source: .
    after: [printer-components, desktop-ubuntu-app-platform]

  printer-components:
    plugin: cmake
    configflags: [-DCMAKE_INSTALL_PREFIX=/usr]
    source: https://code.launchpad.net/~phablet-team/ubuntu-settings-components/printer-components
    source-type: bzr
    build-packages:
     - cmake-extras
     - libcups2-dev
     - libqt5printsupport5
     - debhelper
     - gettext
     - pkg-config
     - python3
     - qml-module-qt-labs-folderlistmodel
     - qml-module-qtquick-layouts
     - qml-module-qtquick2
     - qml-module-qttest
     - qml-module-ubuntu-components
     - qml-module-ubuntu-thumbnailer0.1
     - qtbase5-dev
     - qtbase5-private-dev
     - qtdeclarative5-dev
     - qtdeclarative5-dev-tools
     - suru-icon-theme
    stage-packages:
     - libcups2
     - libqt5printsupport5

  environment:
    source: snap/
    plugin: dump
